package com.xuechuan.xcedu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xuechuan.xcedu.db.UserDoSelectItemDb;
import com.xuechuan.xcedu.db.UserInfomDb;

import com.xuechuan.xcedu.db.UserDoSelectItemDbDao;
import com.xuechuan.xcedu.db.UserInfomDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDoSelectItemDbDaoConfig;
    private final DaoConfig userInfomDbDaoConfig;

    private final UserDoSelectItemDbDao userDoSelectItemDbDao;
    private final UserInfomDbDao userInfomDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDoSelectItemDbDaoConfig = daoConfigMap.get(UserDoSelectItemDbDao.class).clone();
        userDoSelectItemDbDaoConfig.initIdentityScope(type);

        userInfomDbDaoConfig = daoConfigMap.get(UserInfomDbDao.class).clone();
        userInfomDbDaoConfig.initIdentityScope(type);

        userDoSelectItemDbDao = new UserDoSelectItemDbDao(userDoSelectItemDbDaoConfig, this);
        userInfomDbDao = new UserInfomDbDao(userInfomDbDaoConfig, this);

        registerDao(UserDoSelectItemDb.class, userDoSelectItemDbDao);
        registerDao(UserInfomDb.class, userInfomDbDao);
    }
    
    public void clear() {
        userDoSelectItemDbDaoConfig.clearIdentityScope();
        userInfomDbDaoConfig.clearIdentityScope();
    }

    public UserDoSelectItemDbDao getUserDoSelectItemDbDao() {
        return userDoSelectItemDbDao;
    }

    public UserInfomDbDao getUserInfomDbDao() {
        return userInfomDbDao;
    }

}
