package com.xuechuan.xcedu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xuechuan.xcedu.db.UserInfomDb;
import com.xuechuan.xcedu.db.DownVideoDb;

import com.xuechuan.xcedu.db.UserInfomDbDao;
import com.xuechuan.xcedu.db.DownVideoDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfomDbDaoConfig;
    private final DaoConfig downVideoDbDaoConfig;

    private final UserInfomDbDao userInfomDbDao;
    private final DownVideoDbDao downVideoDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfomDbDaoConfig = daoConfigMap.get(UserInfomDbDao.class).clone();
        userInfomDbDaoConfig.initIdentityScope(type);

        downVideoDbDaoConfig = daoConfigMap.get(DownVideoDbDao.class).clone();
        downVideoDbDaoConfig.initIdentityScope(type);

        userInfomDbDao = new UserInfomDbDao(userInfomDbDaoConfig, this);
        downVideoDbDao = new DownVideoDbDao(downVideoDbDaoConfig, this);

        registerDao(UserInfomDb.class, userInfomDbDao);
        registerDao(DownVideoDb.class, downVideoDbDao);
    }
    
    public void clear() {
        userInfomDbDaoConfig.clearIdentityScope();
        downVideoDbDaoConfig.clearIdentityScope();
    }

    public UserInfomDbDao getUserInfomDbDao() {
        return userInfomDbDao;
    }

    public DownVideoDbDao getDownVideoDbDao() {
        return downVideoDbDao;
    }

}
